// Histórico de versões — exibido em Definições > Release notes.
// Mais recentes em cima. Cada entrada lista o que foi adicionado, alterado e removido.
//
// Para acrescentar uma nova versão: bump APP_VERSION em constants.js e adiciona um
// novo objeto no topo deste array, na mesma forma.

export const RELEASE_NOTES = [
  {
    version: "v2.0.0-alpha.27",
    date: "2026-07-11",
    title: "Sprint 3 — Portal Responsável: Timeline de evolução + resumo semestral",
    added: [
      "Novo card EvolutionTimeline por filho no Portal Responsável (HomeTab). Mostra últimas 6 notas de sessão com data, progresso, trabalho realizado e próximo foco.",
      "Sumário semestral 3 KPIs: nº de sessões realizadas, faltas, áreas trabalhadas. Chips das áreas (domains) da sessão.",
      "GlossaryText aplicado nos campos progress/work_done/next_focus da timeline — termos técnicos ficam com underline dotted âmbar e definição no hover/tap.",
      "Visualmente: timeline vertical com dots âmbar sobre linha bege, agrupado por Card com gradient sutil.",
    ],
    changed: [],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.26",
    date: "2026-07-11",
    title: "Sprint 2 — Vista Ano/IRS + CSV + Recibo imprimível no Portal Profissional",
    added: [
      "Nova sub-vista no tab Financeiro: Ano / IRS. Mostra 3 KPIs (Ano recebido / Casa 20% / Você líquido), tabela por mês (nº pag., total, recebido, pendente) com linha TOTAL e card IRS resumo.",
      "Exportar CSV: mensal (todas as colunas do pagamento) e anual (agregado por mês).",
      "Recibo imprimível — modal por pagamento pago com número/nome/mês/data/método/valor e botão Imprimir. CSS @media print oculta tudo exceto o recibo.",
      "Switcher tabs Mensal / Ano dentro do tab Financeiro do Portal Profissional.",
    ],
    changed: [
      "Row de pagamento no Portal Profissional ganha botão Recibo quando o estado é pago.",
    ],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.25",
    date: "2026-07-11",
    title: "Sprint 1 — Pagamentos passam a ser geridos pelo Profissional",
    added: [
      "Novo tab Financeiro no Portal Profissional (desktop + mobile) com KPIs (Total / Recebido / Pendente), distribuição Casa {CLINIC_CUT}% / você {1-CLINIC_CUT}%, filtro por mês, lista de pagamentos e ações inline (togglePayment, deletePayment).",
      "Registar pagamento inline sem passar pelo admin: paciente, mês, valor, estado, método (Transferência / MB WAY / Numerário / Multibanco), notas.",
      "Store actions: createPayment (headless), deletePayment, updatePayment. addPayment agora grava professional_id denormalizado no doc payments (inferido do paciente).",
      "Director-também-profissional: se o utilizador Diretor estiver ligado a um registo em professionals via profile_id, a sidebar admin ganha secção MEU CONSULTÓRIO com atalho /meu-financeiro — vista pessoal, separada do agregado Finance da Casa.",
      "MyFinance (app/src/pages/admin/MyFinance.jsx) reusa o componente ProFinance exportado do Portal Profissional.",
      "Payload de pagamento estendido com campos method e notes.",
    ],
    changed: [
      "Tab bar mobile do Portal Profissional passa de 4 para 5 slots (Início / Agenda / Pacientes / Finan. / Conta) com badge de pendentes.",
      "NAV desktop do Portal Profissional adiciona Financeiro entre Pacientes e Conta.",
      "ProFinance é agora um named export do ProfessionalPortal.jsx.",
    ],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.24",
    date: "2026-07-11",
    title: "FAQ / Perguntas Frequentes — página dedicada",
    added: [
      "Página /faq com 9 perguntas frequentes em PT (psicomotricidade, sessões, trocas, faltas, pagamentos, relatórios, comparticipações ADSE/SAMS/ADM, contactos, exercícios em casa).",
      "Design: FeaturedIcon (48px, tile creme com border), texto centrado, grid auto-fit, CTA final Falar connosco (mailto).",
      "Rota acessível para todos os utilizadores (não-autenticado + parent + pro + director) e link em Account tabs (Responsável e Profissional) + AdminLayout sidebar secção SISTEMA.",
      "Novos ícones em lib/icons.jsx: heart, chat, info, question.",
    ],
    changed: [],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.23",
    date: "2026-07-11",
    title: "ViewToggle — alternar mobile/desktop manualmente",
    added: [
      "ViewToggle chip navy floating bottom-right (br) em Portais Responsável e Profissional. Permite forçar vista Mobile, Desktop, ou Automático (segue viewport).",
      "Escolha persistida em localStorage.psm.view.override e sincronizada entre tabs via storage event.",
      "Hook useViewMode() partilhado em app/src/lib/useViewMode.js.",
    ],
    changed: [
      "Removida a função useIsMobile local dos dois portais — substituída pelo hook central.",
    ],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.22",
    date: "2026-07-11",
    title: "Desktop full — sidebar navy nos Portais Responsável e Profissional",
    added: [
      "Portal Responsável (desktop ≥900px): layout grid 260px + 1fr. Sidebar navy com brand, secção MEUS FILHOS (cada filho como item com foto e dia), NAVEGAÇÃO (4 links com badge de pedidos), perfil no fundo com foto + toggle tema + logout.",
      "Portal Profissional (desktop ≥900px): mesmo layout. Secção HOJE lista sessões do dia com hora inline. NAVEGAÇÃO com badge de mensagens não respondidas. Perfil no fundo.",
      "Hook useIsMobile em ambos portais reage a matchMedia (max-width: 899.98px) para trocar entre render mobile e desktop sem reload.",
    ],
    changed: [
      "Mobile continua com top-bar + bottom tab bar (iOS-like). Desktop deixa de mostrar a bottom tab bar em portais e passa a mostrar sidebar.",
    ],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.21",
    date: "2026-06-22",
    title: "Sprint 4 finale — Onboarding tour + FAQ glossário psicomotor",
    added: [
      "OnboardingTour (C1) — overlay first-run com 3 slides per role (parent / professional / director). Aparece 800ms após entrada, persistido em localStorage.psm.onboarding.done.<userId>. Botão 'Saltar' termina.",
      "Glossário psicomotor (C2) — 20 termos técnicos (coordenação motora, esquema corporal, praxias, M-ABC-2, percentil, etc.) em app/src/lib/glossary.js.",
      "GlossaryText component — auto-highlight de termos do glossário em textos. Underline dotted âmbar; hover/tap mostra popover navy com definição.",
      "Aplicado em ParentPortal SessionsTab — campo 'Evolução observada' das notas de sessão detecta e destaca termos técnicos para pais entenderem.",
    ],
    changed: [
      "Fim do plano de 15 tasks × 4 sprints. Todos os itens A, B, C entregues (com MVP scope).",
    ],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.20",
    date: "2026-06-22",
    title: "Sprint 4 quase — Diário comportamento + Chat + Notificação prefs",
    added: [
      "Diário de comportamento (B4): botão 'Diário' em cada ChildCard do Portal Responsável. Modal com escala humor (5 emojis), horas sono, chips eventos notáveis (birra, conquista, escola difícil...), preocupações. Últimas 5 entradas mostradas inline. Insert em behavior_diary.",
      "Chat parent ↔ terapeuta (B3): botão 'Falar' em ChildCard do Responsável abre modal com histórico + textarea (rate limit: 1 mensagem por vez, aguarda resposta). ProHome do Profissional mostra card amarelo 'Mensagens por responder' com contador; click abre modal de resposta e marca como lida.",
      "Notification preferences (C3): componente NotifPrefs em Account tab do Responsável (Lembretes / Anúncios / Estado pedidos) e ProNotifPrefs no Profissional (Anúncios / Mensagens / Lembretes). Toggles iOS-style guardados em profiles.notification_prefs. Cloud Functions respeitam a leitura no envio.",
    ],
    changed: [
      "ChildCard do Portal Responsável: CTA único 'Pedir troca de horário' passa a grid 3-col com Diário + Falar + Troca (small buttons).",
      "ProHome Profissional: quando há mensagens não respondidas, aparece card amarelo destacado no topo antes de anúncios e sessões.",
    ],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.19",
    date: "2026-06-22",
    title: "Sprint 3 partial — Pro atribui exercícios + Speech-to-text",
    added: [
      "Portal Profissional: em cada paciente, novo botão 'Atribuir exercício' abre modal com dropdown da biblioteca + notas custom para o responsável. Cria home_practice_assignments com professional_id=pro. Vista das atribuições ativas mostra-se logo abaixo do paciente com botão remover.",
      "Speech-to-text no modal de nota de sessão — 4 textareas (Trabalho realizado, Observações clínicas, Evolução, Próximo plano) ganham botão 'Ditar' que usa Web Speech API (SpeechRecognition, pt-PT). Só aparece se browser suporta. Continuous mode: toca uma vez para começar, outra para parar. Texto vai sendo appended ao campo.",
      "components/DictateButton.jsx — componente auto-contido. Pulse na barra de gravação. Suporte: Chrome/Edge OK, Safari parcial, Firefox não (botão não aparece).",
    ],
    changed: [
      "ModalsHost sessionNote: labels dos 4 campos textareas passam a ser JSX com botão Ditar inline à direita.",
    ],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.18",
    date: "2026-06-22",
    title: "Sprint 1+2 — Portal desktop tweaks, Dashboard Hoje, Lista de espera, Biblioteca exercícios, Plano de casa",
    added: [
      "Dashboard Hoje widget — grid 2 col: sessões de hoje (com marcador OK se nota realizada) + alertas (aniversários 3d, pedidos pendentes, faltas hoje, pagamentos por cobrar). Click qualquer item navega.",
      "Lista de espera (CRM leads) em /lista-espera — table-style com Av + sort + filter por estado (6 estados: novo, contactado, reunião, anamnese, ativado, arquivado). Adicionar, editar, mudar estado inline, eliminar.",
      "Biblioteca de exercícios em /exercicios — CRUD com título, descrição, URL vídeo (YouTube/Vimeo), domínios psicomotores multi-select, frequência, duração, dificuldade.",
      "Portal Responsável — nova tab 'Casa' (substituiu Sessões): mostra exercícios atribuídos pelo terapeuta por filho, com vídeo, notas do terapeuta, e botão 'Marcar feito hoje'. Streak counter para dias seguidos.",
      "Store novas colecções: waitlist, home_exercises_library, home_practice_assignments, home_practice_completions, parent_messages, behavior_diary — todos com listeners onSnapshot.",
      "Store novas actions: addWaitlist / updateWaitlist / deleteWaitlist / addHomeExercise / deleteHomeExercise / assignHomeExercise / unassignHomeExercise / markCompletion / sendParentMessage / replyToParent / markMessageRead / addBehaviorEntry / setNotificationPrefs.",
      "Design plano markdown em docs/superpowers/plans/ com 15 tasks × 4 sprints — Sprint 1 (parity + tweaks) + Sprint 2 (director wins) entregues; Sprint 3 (Home Practice UI restante em Pro + Diary + STT) + Sprint 4 (Chat + Onboarding + FAQ + Prefs) documentados no plano para próximo lote.",
      "Sidebar director: 2 novas entradas em CLÍNICO — Lista de espera + Biblioteca exerc.",
      "Design tokens per-breakpoint (--card-pad, --page-pad, --heading-lg, --heading-md) com media query em index.css.",
      "Portais desktop tweaks (A1+A2): tab bar bottom-fixed vira sticky-top em desktop (≥900px); content max-width 1100px; nav horizontal centrado.",
    ],
    changed: [
      "Dark mode fix — html.dark seletores actualizados para novos hex Brand Aligned (#F7F9FB body, #FFFFFF cards, #F5F2EC surfaceAlt, #EAE6DD border). Antes rules matched hex legacy que já não estão no código, resultando em dark mode a não aplicar.",
      "ParentPortal AccountTab signature — recebe agora setNotificationPrefs + users para futuro toggle de preferências (Sprint 4).",
    ],
    removed: [
      "Tab 'Sessões' do Portal Responsável — merged em Home (recentes por filho). Substituído por tab 'Casa' de Plano de Casa.",
    ],
  },
  {
    version: "v2.0.0-alpha.17",
    date: "2026-06-22",
    title: "Fotos de perfil em todos os portais + reset+seed demo + tokens body cool-gray",
    added: [
      "Photo upload em todos os perfis: sidebar director (Lote anterior), agora também tab Conta do Portal Responsável e do Portal Profissional. Popover com Carregar/Trocar/Remover.",
      "Store: updateMyPhoto(file) e removeMyPhoto — resize 256×256 client-side (canvas), JPEG 0.85, guarda como data URL em profiles.photo_url.",
      "Store: resetAndSeedDemo — apaga tudo excepto director actual e cria trio Inês Mota (pro) + Ana Silva (parent stub) + Beatriz Sá (paciente vinculada aos 2) com plano, anamnese, 3 notas, 2 pagamentos, 1 anúncio.",
      "Settings: nova secção 'DEMO / TESTE' com botão para executar reset+seed (só admin).",
      "Av component: prop photoUrl — mostra imagem cover em vez de iniciais quando presente.",
      "Sidebar director com 4 secções + dividers (PRINCIPAL / CLÍNICO / GESTÃO / SISTEMA) + badge âmbar com contador de pedidos pendentes.",
      "RoleSwitcher (chip top-right, só ADMIN_EMAIL): trocar entre Diretor / Profissional / Responsável para testar layouts sem sair da conta admin.",
      "Fotos no greeting: Dashboard 'Boa tarde' com Av 64px, portais Home com Av 56px, top bar mobile com Av 34px.",
      "Design doc: docs/superpowers/plans/2026-06-22-portals-parity-plus-winning-features.md com plano de sprints para A1/A2 (desktop portals), B1-B7 (features vencedoras), C1-C3 (polish).",
    ],
    changed: [
      "Body pages passam de branco #FFFFFF para cool-gray #F7F9FB (AdminLayout desktop+mobile, Privacy, ConfirmSession). Cards mantêm-se brancos puros — hierarquia visual clara.",
      "Cards paper de #FBFAF7 (cream tint) para #FFFFFF (branco puro) via sed global .jsx.",
      "Btn secondary: hover #F7F4EE → #F5F2EC (mais fresco, alinhado com nova palette).",
      "Sidebar director: remove eyebrow 'NAVEGAÇÃO' global; secções têm eyebrows próprias com letras mais espaçadas.",
      "Portais top bar / bottom tab bar mobile: blur translúcido sobre branco (era cream).",
    ],
    removed: [
      "Item 'Auditoria' da sidebar admin (fica acessível via Definições se necessário) — reduz ruído.",
    ],
  },
  {
    version: "v2.0.0-alpha.16",
    date: "2026-06-13",
    title: "Privacidade dinâmica + testes.html + skill psm-testes",
    added: [
      "app/src/lib/privacyPolicy.js — política RGPD em estrutura data-driven (13 secções, blocos p/list/table/kv/callout) com PRIVACY_VERSION + LAST_UPDATE. Editar conteúdo = mexer só nesse ficheiro.",
      "Privacy.jsx refeita: índice sticky lateral (desktop) / topo (mobile), search interno, scroll-to-section via id, renderer por tipo de bloco, link Voltar, contador de versão. Conteúdo cobre: controller, dados, finalidades, base legal RGPD, papéis de acesso, retenção, subprocessadores, direitos, segurança, cookies, menores, alterações, contacto.",
      "testes.html na raiz — documento vivo de QA. 3 tabs (plano/mapa/segurança). Gate Firebase Auth (locked por defeito; só visível com sessão na app). 16 grupos de testes (T1-T16) com persistência em localStorage, contador, filtro, print. Mapa de dados (4 layers + 12 entidades Firestore com fields e links). Segurança (resolvidos + recomendados + controlos implementados + acções próximas).",
      ".claude/skills/psm-testes/SKILL.md — skill instala-vel localmente que guia atualizações ao testes.html (estrutura GROUPS/LAYERS/ENTITIES/SECURITY, regra obrigatória de gate, comando de validação JS).",
    ],
    changed: [],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.15",
    date: "2026-06-13",
    title: "Redesign Brand Aligned — primeira passagem (whites + navy + amber)",
    added: [],
    changed: [
      "Background global passou de cream #F7F4EE para branco #FFFFFF. AdminLayout (desktop + mobile), Login, ConfirmSession, Privacy.",
      "Tokens cream → tons mais frescos: paper #FBF9F4 → #FBFAF7 (cards), cream-2 #EFEBE2 → #F5F2EC (headers de tabela, hover), line #E5E0D4 → #EAE6DD (borders mais subtis).",
      "Top bars / tab bars dos portais Responsável e Profissional: blur translúcido sobre branco em vez de cream.",
      "Btn secondary: bg branco, hover surfaceAlt — destaca-se contra fundo branco em vez de fundir.",
      "CSS var --cream-inverse preserva F7F4EE para texto inverso em fundo navy (sidebar, modais escuros).",
      "Sidebar navy + amber accent mantidos exactamente como antes — só o canvas mudou.",
    ],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.14",
    date: "2026-06-13",
    title: "Style Lab — 3 direcções visuais para redesign",
    added: [
      "Página /style-lab com 3 variantes lado-a-lado: Mono Navy (minimal SaaS), Brand Aligned (navy+amber), Sage Fresh (verde do logo). Cada uma renderiza sidebar/topbar/KPIs/tabela/botões com tokens próprios — preview real antes de commit.",
      "Cores do logo: navy #152741 e sage #8DBF94 como primárias. Sem indigo.",
    ],
    changed: [],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.13",
    date: "2026-06-13",
    title: "Otimização Firestore — listeners + cache + limits reais (-90% reads)",
    added: [
      "Cache persistente IndexedDB (persistentLocalCache + persistentMultipleTabManager) — Firestore SDK serve dados em cache local, multi-tab safe",
      "Listeners em tempo real (onSnapshot) em todas as 14 colecções — primeiro ligar paga as reads, depois só docs alterados são facturados",
      "Limits e where/orderBy aplicados *server-side* — Firestore deixa de devolver colecções inteiras só para serem cortadas no cliente",
      "Visits restringidas aos últimos 30 dias (where ts >= 30d) — antes pull de toda a colecção crescendo a cada login",
      "Listeners director-only para audit_log e visits — parents/pros já nem subscrevem (rules bloqueavam mas tentativa custava ruído na consola)",
    ],
    changed: [
      "store.jsx: load() agora é no-op compatível — `await load()` em acções não custa nada, listeners propagam mutações automaticamente",
      "firebase.js: _run() select usa query(col, ...constraints) com where/orderBy/limit reais; ignora where('id') que Firestore não aceita directamente",
      "firebase.js: db, query, where, orderBy, limit, onSnapshot, getCountFromServer exportados para uso directo em store.jsx",
    ],
    removed: [
      "Polling com Promise.all de 14 getDocs() em cada open + após cada mutação — substituído por subscriptions persistentes",
    ],
  },
  {
    version: "v2.0.0-alpha.12",
    date: "2026-06-08",
    title: "Fix: auto-recovery de chunks órfãos após deploy",
    added: [
      "lazyWithRetry — wrapper de React.lazy que detecta falha de fetch de chunk (utilizador com index.html antigo após deploy novo) e força location.reload() uma vez para apanhar o index novo. Limpa flag após 5s para permitir nova recuperação em futuros deploys.",
    ],
    changed: [
      "App.jsx: todas as importações lazy passam por lazyWithRetry. Utilizadores com sessões antigas deixam de ver 'Failed to fetch dynamically imported module' — recovery silencioso por reload automático.",
    ],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.11",
    date: "2026-06-08",
    title: "Fix: banner de notificações esconde-se até servidor configurado",
    added: [],
    changed: [
      "PushPermissionBanner: agora oculta-se completamente se FCM_VAPID_KEY estiver vazia (servidor ainda não configurado). Evita oferecer ao utilizador algo que falha sempre.",
    ],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.10",
    date: "2026-06-06",
    title: "Push notifications + Confirmar sessão 1-tap",
    added: [
      "Service worker unificado (cache PWA + FCM background messages)",
      "Push notifications de 3 tipos: lembrete de sessão amanhã, novo anúncio, estado de pedido (aprovado/recusado)",
      "PushPermissionBanner — pede permissão ao utilizador (auto-dismiss após 7 dias)",
      "Página /confirmar/:patientId/:date — fluxo opt-out: 'Tudo OK' ou 'Não posso ir' (com motivo opcional). Cria nota de sessão com status=cancelado",
      "store.enablePush()/disablePush()/cancelSession() + pushState",
      "fcm helpers em firebase.js (requestPermissionAndToken, deleteToken, onForegroundMessage, saveTokenToProfile)",
      "Cloud Functions (functions/index.js): sessionReminders (Cloud Scheduler 18:00 Lisboa), onAnnouncementCreated, onScheduleRequestUpdated",
      "Limpeza automática de tokens FCM inválidos (pruneInvalidTokens) — após erro, remove do profile",
    ],
    changed: [
      "App.jsx: rota /confirmar/:patientId/:date acessível a todos os perfis autenticados",
      "App.jsx: PushListener — foreground messages aparecem como toast; postMessage do SW navega para o URL alvo",
      "firestore.rules: session_notes ganha excepção — responsáveis podem criar nota cancelled_by_user=true (necessário para o fluxo 'Não posso ir')",
      "sw.js renomeado conceptualmente — agora é o registado service worker, inclui firebase-messaging-compat",
      "functions/index.js: lembretes agora enviam push (preferido) + email (complementar via Resend)",
    ],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.9",
    date: "2026-05-27",
    title: "PWA, code splitting, vínculo profissional, regras Firestore",
    added: [
      "PWA — manifest.webmanifest, icon.svg, apple-touch-icon.svg, service worker (cache-first em /assets, network-first com fallback offline para HTML). Install no iPhone via 'Adicionar ao Ecrã Principal'",
      "Code splitting — todas as páginas admin e portais carregadas com React.lazy + Suspense. O bundle inicial baixa só Login + Dashboard + shell; o resto vem on-demand",
      "Vínculo conta ↔ profissional — ProfDetail (admin → Equipa) ganha card 'Conta vinculada' com modal de seleção (apenas perfis role=professional). O Portal Profissional usa profile_id explícito antes do fallback por nome",
      "PageLoader iOS-style durante Suspense (mark + spinner mono)",
    ],
    changed: [
      "firestore.rules atualizadas — colecção announcements (read autenticados, write director); schedule_requests aceita create de qualquer autenticado (parent submete pedidos); anamnesis/notes/plans read aberto a autenticado para o portal do responsável funcionar (filtragem por parent_user_ids no cliente)",
      "App.jsx — VisitLogger e ToastHost mantidos, mas os componentes de página estão atrás de Suspense + ErrorBoundary",
      "Team.jsx — ProfDetail layout em 2 colunas (perfil+conta vinculada / KPIs+casos); usa patient-grid CSS para empilhar em mobile",
      "ProfessionalPortal — findMyProfRecord aceita profile.id como primeiro argumento; profile_id tem prioridade",
      "store: setProfessionalUser(professionalId, userId) — director vincula/desvincula conta",
    ],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.8",
    date: "2026-05-26",
    title: "Comunicações, vinculação de responsáveis e mais",
    added: [
      "Página Comunicações (admin) — director publica anúncios visíveis nos portais Profissional e/ou Responsável; podem ser activadas/desactivadas/eliminadas",
      "Vinculação explícita responsável↔paciente — em PatientDetail, novo botão 'Vincular contas' abre modal para selecionar perfis com role=parent; o portal do responsável passa a usar parent_user_ids como matching preferencial (com fallback para o nome)",
      "Portal Profissional — botão rápido 'Marcar falta' nas sessões de hoje (cria nota com status=falta)",
      "Portal Profissional — secção 'Aniversários · 30 dias' dos meus pacientes",
      "Portal Profissional — banner de anúncios da direção no topo",
      "Portal Responsável — banner de anúncios da direção no topo",
      "Portal Responsável — separador 'Pedidos' mostra histórico completo com estado (Pendente / Aprovado / Recusado) e os horários antes→depois",
      "Portal Responsável — badge vermelho na tab 'Pedidos' quando há pedidos respondidos desde a última visita; banner 'Novidades' na Home",
    ],
    changed: [
      "store.jsx: nova colecção announcements + acções addAnnouncement/toggleAnnouncementActive/deleteAnnouncement",
      "store.jsx: quickMarkFalta(patientId, profId) e setPatientParents(patientId, ids)",
      "store.jsx: schedule_requests deixa de ser filtrada por status na store; admin Requests passa a filtrar localmente para o responsável poder ver o histórico",
      "store.jsx: approveRequest/rejectRequest gravam updated_at (necessário para detecção de novidades no portal)",
      "Admin Requests: agora distingue origem do pedido (Profissional vs Responsável) e mostra horários antes→depois para ambos os formatos",
      "Patients: addPatient agora persiste parent_user_ids",
      "Sidebar admin: nova entrada Comunicações entre Pedidos e Definições",
    ],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.7",
    date: "2026-05-26",
    title: "Portais Responsável & Profissional · Release notes",
    added: [
      "Portal do Responsável — vê filhos, próximas sessões, plano de intervenção, últimas notas e pagamentos",
      "Portal do Profissional — agenda da semana, pacientes atribuídos, registo rápido de nota de sessão",
      "Esta página de Release notes em Definições (com histórico completo)",
      "ErrorBoundary global — em vez de páginas em branco mostra mensagem de erro + stack",
    ],
    changed: [
      "App: routing por papel (Diretor/Profissional/Responsável) com StoreProvider partilhada na raiz",
      "ModalsHost e Toast movidos para o topo da app (acessíveis a todos os portais)",
      "Identificação de pacientes por responsável: match (case-insensitive) entre profile.full_name e parent_mother/parent_father",
      "Identificação por profissional: match entre profile.full_name e professionals.name",
    ],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.6",
    date: "2026-05-26",
    title: "Mobile responsive + iOS-feel",
    added: [
      "Bottom tab bar mobile (Dashboard, Pacientes, Agenda, Mais) com top app bar translúcida e blur",
      "Bottom sheet (slide-up) em vez de modal centrado em mobile",
      "Segmented control de dias na Agenda mobile (toca para mudar de dia)",
      "Pacientes em lista de cards em mobile (tabela mantém-se em desktop)",
      "Footer com versão e data da última atualização — auto via Vite build-time (__BUILD_DATE__)",
      "Configuração Vercel (vercel.json à raiz) para auto-deploy em cada push",
      "Safe-area insets (notch / home indicator do iPhone)",
    ],
    changed: [
      "Tipografia: -apple-system como primária, DM Sans secundária",
      "Animações: cubic-bezier(.32,.72,0,1) — curva spring inspirada no iOS",
      "Toast respeita altura da tab bar e safe-area-inset",
      "Inputs mobile com font-size 16px (impede zoom automático no Safari iOS)",
      "Scrollbars escondidos em mobile (estilo nativo)",
    ],
    removed: [
      "Link discreto 'modo escuro' no rodapé da sidebar (substituído por botão sol/lua visível)",
    ],
  },
  {
    version: "v2.0.0-alpha.5",
    date: "2026-05-26",
    title: "Acessibilidade e UX (Lote 6)",
    added: [
      "Focus rings visíveis (:focus-visible) em botões, links e elementos role=button",
      "Skip link 'Saltar para o conteúdo principal'",
      "aria-label em botões de ícone (logout, fechar modal, toggle tema, eliminar)",
      "ConfirmModal acessível (role=dialog, aria-modal, Esc para fechar)",
      "Banner inline 'Conta desativada' no Login (acionado via ?disabled=1)",
      "Toggle de tema (sol/lua) promovido a botão visível na sidebar",
    ],
    changed: [
      "alert() e confirm() nativos substituídos por Modal / Toast / ConfirmModal",
      "Cards e linhas de tabela navegáveis por teclado (Enter / Space)",
      "Toast com role=alert/status e aria-live conforme tipo",
      "Contraste sidebar inactiva subido (.5 → .65–.78) para cumprir WCAG AA",
      "prefers-reduced-motion respeitado (animações desligadas)",
    ],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.4",
    date: "2026-05-24",
    title: "Importação administrativa de pacientes",
    added: [
      "Segundo formato de importação em massa (nome, NIF, seguro, número de seguro)",
    ],
    changed: [],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.3",
    date: "2026-05-23",
    title: "Lote 5 — Auditoria, Export, P&L, Aniversários, RGPD",
    added: [
      "Log de auditoria — registo de todas as acções administrativas",
      "Exportação CSV (pacientes, pagamentos, profissionais, notas, utilizadores)",
      "P&L mensal no Financeiro",
      "Aniversários nos próximos 30 dias no Dashboard",
      "Página de Privacidade (RGPD)",
    ],
    changed: [],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.2",
    date: "2026-05-23",
    title: "Lote 4 — Núcleo clínico",
    added: [
      "Anamnese — ficha de admissão estruturada",
      "Notas de sessão com domínios psicomotores (10 categorias)",
      "Plano de intervenção com objetivos mensuráveis e progresso",
    ],
    changed: [],
    removed: [],
  },
  {
    version: "v2.0.0-alpha.1",
    date: "2026-05-23",
    title: "Lotes 1-3 — Scaffold + migração para Vite",
    added: [
      "Nova versão modular em /app (Vite + React Router + Firebase)",
      "Autenticação Firebase (email/password e Google)",
      "Páginas: Dashboard, Utilizadores, Equipa, Pacientes (lista + detalhe)",
      "Agenda semanal (grelha dias × horas)",
      "Financeiro (pagamentos, custos fixos e variáveis)",
      "Pedidos de troca de horário",
      "Definições com acções rápidas e exports",
      "Modo escuro (toggle global)",
    ],
    changed: [
      "Migração de Supabase → Firebase via adaptador 'sb' (mesma API)",
    ],
    removed: [],
  },
];

// Total de versões — usado para badges/contadores.
export const RELEASE_NOTES_COUNT = RELEASE_NOTES.length;
